// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: protodata/consensus.proto

package protodata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConsensusClient is the client API for Consensus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsensusClient interface {
	// Sends a greeting
	SendRecord(ctx context.Context, in *WalEntry, opts ...grpc.CallOption) (*WalResponse, error)
	Ack(ctx context.Context, in *Hearbeat, opts ...grpc.CallOption) (*HearbeatResponse, error)
	Get(ctx context.Context, in *GetKey, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetKey, opts ...grpc.CallOption) (*SetKeyResponse, error)
	GetMany(ctx context.Context, in *GetSeveralKeys, opts ...grpc.CallOption) (*GetSeveralResponse, error)
	Broadcast(ctx context.Context, in *BroadcastNode, opts ...grpc.CallOption) (*BroadcastNodeResponse, error)
	Vote(ctx context.Context, in *VoteNode, opts ...grpc.CallOption) (*VoteNodeResponse, error)
	LeaderInfo(ctx context.Context, in *AskLeader, opts ...grpc.CallOption) (*LeaderInfoResponse, error)
}

type consensusClient struct {
	cc grpc.ClientConnInterface
}

func NewConsensusClient(cc grpc.ClientConnInterface) ConsensusClient {
	return &consensusClient{cc}
}

func (c *consensusClient) SendRecord(ctx context.Context, in *WalEntry, opts ...grpc.CallOption) (*WalResponse, error) {
	out := new(WalResponse)
	err := c.cc.Invoke(ctx, "/consensus.Consensus/SendRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusClient) Ack(ctx context.Context, in *Hearbeat, opts ...grpc.CallOption) (*HearbeatResponse, error) {
	out := new(HearbeatResponse)
	err := c.cc.Invoke(ctx, "/consensus.Consensus/Ack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusClient) Get(ctx context.Context, in *GetKey, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/consensus.Consensus/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusClient) Set(ctx context.Context, in *SetKey, opts ...grpc.CallOption) (*SetKeyResponse, error) {
	out := new(SetKeyResponse)
	err := c.cc.Invoke(ctx, "/consensus.Consensus/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusClient) GetMany(ctx context.Context, in *GetSeveralKeys, opts ...grpc.CallOption) (*GetSeveralResponse, error) {
	out := new(GetSeveralResponse)
	err := c.cc.Invoke(ctx, "/consensus.Consensus/GetMany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusClient) Broadcast(ctx context.Context, in *BroadcastNode, opts ...grpc.CallOption) (*BroadcastNodeResponse, error) {
	out := new(BroadcastNodeResponse)
	err := c.cc.Invoke(ctx, "/consensus.Consensus/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusClient) Vote(ctx context.Context, in *VoteNode, opts ...grpc.CallOption) (*VoteNodeResponse, error) {
	out := new(VoteNodeResponse)
	err := c.cc.Invoke(ctx, "/consensus.Consensus/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensusClient) LeaderInfo(ctx context.Context, in *AskLeader, opts ...grpc.CallOption) (*LeaderInfoResponse, error) {
	out := new(LeaderInfoResponse)
	err := c.cc.Invoke(ctx, "/consensus.Consensus/LeaderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsensusServer is the server API for Consensus service.
// All implementations must embed UnimplementedConsensusServer
// for forward compatibility
type ConsensusServer interface {
	// Sends a greeting
	SendRecord(context.Context, *WalEntry) (*WalResponse, error)
	Ack(context.Context, *Hearbeat) (*HearbeatResponse, error)
	Get(context.Context, *GetKey) (*GetResponse, error)
	Set(context.Context, *SetKey) (*SetKeyResponse, error)
	GetMany(context.Context, *GetSeveralKeys) (*GetSeveralResponse, error)
	Broadcast(context.Context, *BroadcastNode) (*BroadcastNodeResponse, error)
	Vote(context.Context, *VoteNode) (*VoteNodeResponse, error)
	LeaderInfo(context.Context, *AskLeader) (*LeaderInfoResponse, error)
	mustEmbedUnimplementedConsensusServer()
}

// UnimplementedConsensusServer must be embedded to have forward compatible implementations.
type UnimplementedConsensusServer struct {
}

func (UnimplementedConsensusServer) SendRecord(context.Context, *WalEntry) (*WalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRecord not implemented")
}
func (UnimplementedConsensusServer) Ack(context.Context, *Hearbeat) (*HearbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedConsensusServer) Get(context.Context, *GetKey) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedConsensusServer) Set(context.Context, *SetKey) (*SetKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedConsensusServer) GetMany(context.Context, *GetSeveralKeys) (*GetSeveralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMany not implemented")
}
func (UnimplementedConsensusServer) Broadcast(context.Context, *BroadcastNode) (*BroadcastNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedConsensusServer) Vote(context.Context, *VoteNode) (*VoteNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedConsensusServer) LeaderInfo(context.Context, *AskLeader) (*LeaderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaderInfo not implemented")
}
func (UnimplementedConsensusServer) mustEmbedUnimplementedConsensusServer() {}

// UnsafeConsensusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsensusServer will
// result in compilation errors.
type UnsafeConsensusServer interface {
	mustEmbedUnimplementedConsensusServer()
}

func RegisterConsensusServer(s grpc.ServiceRegistrar, srv ConsensusServer) {
	s.RegisterService(&Consensus_ServiceDesc, srv)
}

func _Consensus_SendRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServer).SendRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consensus.Consensus/SendRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServer).SendRecord(ctx, req.(*WalEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensus_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hearbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consensus.Consensus/Ack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServer).Ack(ctx, req.(*Hearbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensus_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consensus.Consensus/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServer).Get(ctx, req.(*GetKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensus_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consensus.Consensus/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServer).Set(ctx, req.(*SetKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensus_GetMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeveralKeys)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServer).GetMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consensus.Consensus/GetMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServer).GetMany(ctx, req.(*GetSeveralKeys))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensus_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consensus.Consensus/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServer).Broadcast(ctx, req.(*BroadcastNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensus_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consensus.Consensus/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServer).Vote(ctx, req.(*VoteNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensus_LeaderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskLeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServer).LeaderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consensus.Consensus/LeaderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServer).LeaderInfo(ctx, req.(*AskLeader))
	}
	return interceptor(ctx, in, info, handler)
}

// Consensus_ServiceDesc is the grpc.ServiceDesc for Consensus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consensus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.Consensus",
	HandlerType: (*ConsensusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRecord",
			Handler:    _Consensus_SendRecord_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _Consensus_Ack_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Consensus_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Consensus_Set_Handler,
		},
		{
			MethodName: "GetMany",
			Handler:    _Consensus_GetMany_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _Consensus_Broadcast_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Consensus_Vote_Handler,
		},
		{
			MethodName: "LeaderInfo",
			Handler:    _Consensus_LeaderInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protodata/consensus.proto",
}
