global:
  scrape_interval: 2s
scrape_configs:
- job_name: node2837
  static_configs:
  - targets:
    - node2837:8080
    labels:
      instance: node2837
- job_name: node6279
  static_configs:
  - targets:
    - node6279:8080
    labels:
      instance: node6279
- job_name: node11433
  static_configs:
  - targets:
    - node11433:8080
    labels:
      instance: node11433
- job_name: node21024
  static_configs:
  - targets:
    - node21024:8080
    labels:
      instance: node21024
- job_name: node21267
  static_configs:
  - targets:
    - node21267:8080
    labels:
      instance: node21267
