global:
  scrape_interval: 2s
scrape_configs:
- job_name: node70301
  static_configs:
  - targets:
    - node70301:8080
    labels:
      instance: node70301
- job_name: node471
  static_configs:
  - targets:
    - node471:8080
    labels:
      instance: node471
- job_name: node23593
  static_configs:
  - targets:
    - node23593:8080
    labels:
      instance: node23593
- job_name: node7321
  static_configs:
  - targets:
    - node7321:8080
    labels:
      instance: node7321
- job_name: node40267
  static_configs:
  - targets:
    - node40267:8080
    labels:
      instance: node40267
