global:
  scrape_interval: 2s
scrape_configs:
- job_name: node69146
  static_configs:
  - targets:
    - node69146:8080
    labels:
      instance: node69146
- job_name: node79401
  static_configs:
  - targets:
    - node79401:8080
    labels:
      instance: node79401
- job_name: node94248
  static_configs:
  - targets:
    - node94248:8080
    labels:
      instance: node94248
- job_name: node69805
  static_configs:
  - targets:
    - node69805:8080
    labels:
      instance: node69805
- job_name: node20770
  static_configs:
  - targets:
    - node20770:8080
    labels:
      instance: node20770
- job_name: node59153
  static_configs:
  - targets:
    - node59153:8080
    labels:
      instance: node59153
