FROM golang:1.19.3-alpine AS src

# Install git

# Copy Repository
WORKDIR /go/src
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
COPY ./ ./

# Build Go Binary

# RUN set -ex; \
    
CMD CGO_ENABLED=0 go test -v  ./... 



