FROM golang:1.19.3-alpine AS src

# Install git

# Copy Repository
WORKDIR /go/src
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
COPY ./ ./

# Build Go Binary

RUN set -ex; \
    CGO_ENABLED=0 GOOS=linux go build -o ./bin/serve ./cmd/client/main.go;
RUN set -ex; \
    CGO_ENABLED=0 GOOS=linux go build -o ./bin/serveClient ./cmd/consensus/main.go;
# CMD ["./serve"]
# Final image, no source code

